const activeSeller = function () {
  return `<!DOCTYPE html><html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en"><head><title></title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]--><!--[if !mso]><!--><link href="https://fonts.googleapis.com/css?family=Cabin" 
rel="stylesheet" type="text/css"><!--<![endif]--><style>
*{box-sizing:border-box}body{margin:0;padding:0}a[x-apple-data-detectors]{color:inherit!important;text-decoration:inherit!important}#MessageViewBody a{color:inherit;text-decoration:none}p{line-height:inherit}.desktop_hide,.desktop_hide table{mso-hide:all;display:none;max-height:0;overflow:hidden}@media (max-width:620px){.desktop_hide table.icons-inner{display:inline-block!important}.icons-inner{text-align:center}.icons-inner td{margin:0 auto}.row-content{width:100%!important}.column .border,.mobile_hide{display:none}table{table-layout:fixed!important}.stack .column{width:100%;display:block}.mobile_hide{min-height:0;max-height:0;max-width:0;overflow:hidden;font-size:0}.desktop_hide,.desktop_hide table{display:table!important;max-height:none!important}}
</style></head><body style="background-color:#fff;margin:0;padding:0;-webkit-text-size-adjust:none;text-size-adjust:none"><table class="nl-container" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff"><tbody><tr><td><table class="row row-1" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table 
class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block" width="100%" border="0" 
cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:18px;color:#8a8a8a;line-height:1.5;font-family:Cabin,Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:center">
<a style="text-decoration: none; color: #851fe5;" title="http://www.example.com" href="http://www.example.com" target="_blank" rel="noopener">View Online</a></p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-2" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" 
cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#12123f;background-image:url(https://d1oco4z2z1fhwp.cloudfront.net/templates/default/2016/background.png);background-position:top center;background-repeat:no-repeat;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:0;padding-bottom:0;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td style="width:100%;padding-right:0;padding-left:0"><div align="right" style="line-height:10px"><img 
src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/2016/ONMTS-1_1.png" style="display:block;height:auto;border:0;width:330px;max-width:100%" width="330" alt="Ornament" title="Ornament"></div></td></tr></table><table class="image_block" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td style="width:100%;padding-right:0;padding-left:0"><div align="center" style="line-height:10px"><img 
src="https://www.shoppit.com.ar/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FlogoTienda.09eb0f6b.png&w=750&q=75" style="display:block;height:auto;border:0;width:120px;max-width:100%" width="120" alt="Your Brand Logo" title="Your Brand Logo"></div></td></tr></table><table class="text_block" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td 
style="padding-bottom:15px;padding-left:25px;padding-right:25px;padding-top:15px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#fff;line-height:1.2;font-family:Cabin,Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:center"><span style="font-size:42px;">Tu cuenta de vendedor ha sido activada con extito</span></p></div></div></td></tr></table><table class="text_block" 
width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td style="padding-bottom:5px;padding-left:30px;padding-right:30px;padding-top:5px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:21.6px;color:#dcdcdc;line-height:1.8;font-family:Cabin,Arial,Helvetica Neue,Helvetica,sans-serif"><p 
style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:28.8px"><span style="font-size:16px;">hemos validados todos tus datos y te damos la bienvenida a la comunidad mas grande de vendedores mayoristas. ya puedes comenzar a publicar tus productos!</span></p></div></div></td></tr></table><table class="button_block" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td 
style="padding-bottom:5px;padding-left:5px;padding-right:5px;padding-top:20px;text-align:center"><div align="center">
<!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="http://www.shoppit.com.ar" style="height:42px;width:154px;v-text-anchor:middle;" arcsize="96%" stroke="false" fillcolor="#851fe5"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#ffffff; font-family:Arial, sans-serif; font-size:16px"><![endif]-->
<a href="http://www.shoppit.com.ar" target="_blank" style="text-decoration:none;display:inline-block;color:#ffffff;background-color:#851fe5;border-radius:40px;width:auto;border-top:1px solid #851fe5;font-weight:400;border-right:1px solid #851fe5;border-bottom:1px solid #851fe5;border-left:1px solid #851fe5;padding-top:5px;padding-bottom:5px;font-family:Cabin, Arial, Helvetica Neue, Helvetica, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:30px;padding-right:30px;font-size:16px;display:inline-block;letter-spacing:normal;"><span style="font-size: 16px; line-height: 2; word-break: break-word; mso-line-height-alt: 32px;">IR A SHOPPIT</span></span></a>
<!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table><table class="text_block" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td style="padding-bottom:10px;padding-left:30px;padding-right:30px;padding-top:10px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" 
style="font-size:12px;mso-line-height-alt:21.6px;color:#dcdcdc;line-height:1.8;font-family:Cabin,Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:12px;mso-line-height-alt:21.6px">&nbsp;</p></div></div></td></tr></table><table class="image_block" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td style="width:100%;padding-right:0;padding-left:0;padding-top:30px"><div style="line-height:10px"><img
 src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/2016/ONMTS-2_1.png" style="display:block;height:auto;border:0;width:330px;max-width:100%" width="330" alt="Ornament" title="Ornament"></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-3" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content" align="center" 
border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0"><tr><td style="padding-bottom:20px;padding-left:10px;padding-right:10px;padding-top:20px;width:100%"><div style="line-height:10px"><img src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/2016/logo-color_1.png" style="display:block;height:auto;border:0;width:60px;max-width:100%" width="60" alt="Black Your Brand Logo" title="Black Your Brand Logo"></div></td></tr></table></td><td class="column column-2" width="50%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="social_block" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td style="padding-bottom:25px;padding-left:15px;padding-right:15px;padding-top:25px;text-align:right"><table class="social-table" width="144px" border="0" cellpadding="0" cellspacing="0" 
role="presentation" align="right" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td style="padding:0 0 0 4px"><a href="https://www.facebook.com/" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-outline-circle-dark-gray/facebook@2x.png" width="32" height="32" alt="Facebook" title="facebook" style="display:block;height:auto;border:0"></a></td><td style="padding:0 0 0 4px"><a href="https://www.twitter.com/" target="_blank"><img 
src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-outline-circle-dark-gray/twitter@2x.png" width="32" height="32" alt="Twitter" title="twitter" style="display:block;height:auto;border:0"></a></td><td style="padding:0 0 0 4px"><a href="https://www.linkedin.com/" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-outline-circle-dark-gray/linkedin@2x.png" width="32" height="32" alt="Linkedin" title="linkedin" 
style="display:block;height:auto;border:0"></a></td><td style="padding:0 0 0 4px"><a href="https://www.instagram.com/" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-outline-circle-dark-gray/instagram@2x.png" width="32" height="32" alt="Instagram" title="instagram" style="display:block;height:auto;border:0"></a></td></tr></table></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-4" align="center" 
width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:0;padding-bottom:0;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" 
style="font-size:12px;mso-line-height-alt:18px;color:#8a8a8a;line-height:1.5;font-family:Cabin,Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:center">Sed a viverra ante. Nullam posuere pellentesque lectus, nec vehicula felis rutrum ac. Maecenas porta facilisis turpis, eget imperdiet purus.</p></div></div></td></tr></table><table class="text_block" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:12px;mso-line-height-alt:14.399999999999999px;color:#8a8a8a;line-height:1.2;font-family:Cabin,Arial,Helvetica Neue,Helvetica,sans-serif"><p style="margin:0;font-size:14px;text-align:center">
<a style="text-decoration: none; color: #851fe5;" title="www.example.com" href="http://www.example.com" target="_blank" rel="noopener">Terms & Conditions</a> | <a style="text-decoration: none; color: #851fe5;" title="http://www.example.com" href="http://www.example.com" target="_blank" rel="noopener">Unsubscribe</a></p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-5" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" 
role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="icons_block" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td style="vertical-align:middle;color:#9d9d9d;font-family:inherit;font-size:15px;padding-bottom:5px;padding-top:5px;text-align:center"><table width="100%" 
cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td style="vertical-align:middle;text-align:center"><!--[if vml]><table align="left" cellpadding="0" cellspacing="0" role="presentation" style="display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;"><![endif]--><!--[if !vml]><!--><table class="icons-inner" 
style="mso-table-lspace:0;mso-table-rspace:0;display:inline-block;margin-right:-4px;padding-left:0;padding-right:0" cellpadding="0" cellspacing="0" role="presentation"><!--<![endif]--><tr><td style="vertical-align:middle;text-align:center;padding-top:5px;padding-bottom:5px;padding-left:5px;padding-right:6px"></td></tr></table></td></tr></table></td></tr></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!-- End --></body></html>`;
};

module.exports = { activeSeller };
