function dtoProduct(product) {
  let image = [];
  image.push(product.featuredImage ?? product.images_url[0]);
  return {
    id: product.id,
    name: product.name,
    regularPrice: product.regular_price,
    ownerId: product.owner_id,
    minSellAmount: product.min_sell_amount,
    features: product.features || product.description || 'sin descripcion',
    totalStock: product.total_stock || product.stock_quantity || 1,
    description: product.features || product.description || 'sin descripcion',
    category: product.category || 'sin categoria',
    imagesUrl: product.images_url || product.images,
    variations: product.variations || [],
    published: product.published || true,
    //createdAt: product.created_at || new Date(),
    freeShipping: product.freeShipping || false,
    categories: [],
    permalink: product.permalink || 'http://www.google.com',
    volumen: product.volumen || 1,
    //availableSizes: product.availableSizes || [],
    longitude: 0,
    shortDescription: product.shortDescription || 'sin descripcion',
    featuredImage: product.featuredImage || 'no image',
    tags: product.tags || [],
    stockQuantity: product.stock_quantity || product.total_stock || 1,
    quantityToCart: product.quantityToCart || 1,
    sku: product.sku || 'sin sku',
    manageStock: product.manage_stock || false,
    selectedVariation: product.selectedVariation || {},
    price: product.regular_price,
    variableProducts: product.variableProducts || [],
    totalSales: product.total_sales || 0,
    featured: product.featured || false,
    productAttributes: product.productAttributes || [],
    manageSize: product.manageSize || false,
    width: 0,
    salePrice: product.sale_price || 0,
    images: image,
    categoriesSub: product.categoriesSub || [],
    inStock: product.inStock || true,
    isPublished: product.published || product.isPublished || true,
    weight: 0,
    availableColors: product.availableColors || [],
    withError: product.withError || false,
    manageColors: product.manageColors || false,
    averageRating: product.average_rating || 0,
    height: 0,
    ratingCount: product.rating_count || 0,
  };
}

module.exports = {
  dtoProduct,
};
